CREATE TABLE WORK (
    ID INT PRIMARY KEY NOT NULL,
    VALUE INT NOT NULL,
    NEARPRIME INT,
    PROCESSEDBY VARCHAR(80)
);

INSERT INTO WORK (id, value) SELECT *, * FROM generate_series(1, 10000);
