#!/usr/bin/env bash

#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License
#

##
## This script removes the two DMZ sites from the cluster.
##

if [ ! -v NP_NAMESPACE_PREFIX ]; then
    NP_NAMESPACE_PREFIX=npdemo
fi

for i in dmz-a dmz-b;
do
kubectl delete accessgrant $i-grant -n ${NP_NAMESPACE_PREFIX}-$i
kubectl delete routeraccess $i-peer -n ${NP_NAMESPACE_PREFIX}-$i
kubectl delete site $i -n ${NP_NAMESPACE_PREFIX}-$i
rm token-$i.yaml
done

kubectl delete accesstoken dmz-a-token -n ${NP_NAMESPACE_PREFIX}-dmz-b
