#!/usr/bin/env bash

#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License
#

##
## This script sets up a remote (worker) site in the current context/namespace 
##

if [ -v $1 ]; then
    echo A site-name must be supplied
    echo usage: $0 '<site-name>'
    exit 1
fi

SITE=$1

echo Create site ${SITE} in current namespace
cat >temp <<EOF
apiVersion: skupper.io/v1alpha1
kind: Site
metadata:
  name: ${SITE}
spec:
  routerMode: "interior"
  ha: false
EOF
kubectl apply -f temp
kubectl apply -f token-dmz-a.yaml
kubectl apply -f token-dmz-b.yaml
rm temp
