#!/usr/bin/env bash

#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License
#

##
## This script creates the on-prem kubernetes site for pre-migrated workloads.
## This site connects to the DMZ and also has a router-access so the Podman site
## can connect to it directly.
##
## This site is created in the current kubernetes context/namespace.
##

if [ -v $1 ]; then
    echo A site-name must be supplied
    echo usage: $0 '<site-name>'
    exit 1
fi

SITE=$1

echo Create site ${SITE} in current namespace
cat >temp <<EOF
apiVersion: skupper.io/v1alpha1
kind: Site
metadata:
  name: ${SITE}
spec:
  routerMode: "interior"
  ha: false
---
apiVersion: skupper.io/v1alpha1
kind: RouterAccess
metadata:
  name: ${SITE}-peer
spec:
  generateTlsCredentials: true
  issuer: skupper-site-ca
  roles:
  - name: inter-router
    port: 55671
  tlsCredentials: skupper-site-server
---
apiVersion: skupper.io/v1alpha1
kind: AccessGrant
metadata:
  name: ${SITE}-grant
spec:
  redemptionsAllowed: 10
  expirationWindow: 1h
EOF
kubectl apply -f temp
kubectl apply -f token-dmz-a.yaml
kubectl apply -f token-dmz-b.yaml
rm temp

echo Generating access token token-${SITE}.yaml

#
# Wait for the access grant to achieve READY state.
#
kubectl wait --for=condition=ready accessgrant/${SITE}-grant

#
# Use the contents from the completed access grant to create an access token.
#
kubectl get accessgrant ${SITE}-grant -o yaml > temp
URL=`cat temp | yq '.status.url'`
CODE=`cat temp | yq '.status.code'`
CA=`cat temp | yq -r '.status.ca' | awk '{ print "    " $0 }'`
cat >token-${SITE}.yaml <<EOF
apiVersion: skupper.io/v1alpha1
kind: AccessToken
metadata:
  name: ${SITE}-token
spec:
  url: ${URL}
  code: ${CODE}
  ca: |
${CA}
EOF

