#!/usr/bin/env bash

#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License
#

##
## This script removes the on-prem kubernetes site from the current context/namespace.
##

SITE=`kubectl get sites -o custom-columns=NAME:.metadata.name --no-headers`

echo Delete site ${SITE} from current namespace
kubectl delete site ${SITE}
kubectl delete accesstoken dmz-a-token dmz-b-token
kubectl delete routeraccess ${SITE}-peer
kubectl delete accessgrant ${SITE}-grant
rm token-${SITE}.yaml
kubectl delete listener postgres
kubectl delete connector nearestprime
kubectl delete deployment nearestprime

