#!/usr/bin/env bash

#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License
#

##
## This script creates the Podman site for access to/from local bare-metal workloads.
##

DIR=declared-site
mkdir ${DIR}

cat >${DIR}/site.yaml <<EOF
apiVersion: skupper.io/v1alpha1
kind: Site
metadata:
  name: legacyhost
spec:
  routerMode: "interior"
  ha: false
EOF

cat >${DIR}/wiring.yaml <<EOF
apiVersion: skupper.io/v1alpha1
kind: Listener
metadata:
  name: nearestprime
spec:
  routingKey: np
  port: 8000
  host: 127.0.0.1
---
apiVersion: skupper.io/v1alpha1
kind: Connector
metadata:
  name: postgres
spec:
  routingKey: db
  port: 5432
  host: 127.0.0.1
EOF

cp token-*.yaml ${DIR}

podman network create skupper

curl -s https://raw.githubusercontent.com/skupperproject/skupper/refs/heads/v2/cmd/bootstrap/bootstrap.sh | sh -s -- -p ./${DIR}
